import type { SampleDatasetInfo } from "@shared/ml";
import type { RawTable } from "./data";
import { Rng } from "./random";

/**
 * Sample datasets. All three are generated by code with a fixed seed, so they
 * are labelled synthetic: the rows are real rows the pipeline really processes,
 * but they describe no real flowers, houses or customers.
 */
export const SAMPLES: (SampleDatasetInfo & { build: () => RawTable; note: string })[] = [
  {
    id: "flowers",
    name: "Flower measurements",
    description: "Three species, four measurements each. Clean, balanced, easy to separate: the classic first classification problem.",
    task: "classification",
    rows: 180,
    synthetic: true,
    suggestedTarget: "species",
    note: "Synthetic: 180 rows drawn from three Gaussian clusters with a fixed seed. The rows are real inputs to every stage; the flowers are not.",
    build: () => {
      const rng = new Rng(7);
      const species = [
        { name: "setosa", mean: [5.0, 3.4, 1.5, 0.25], sd: [0.35, 0.38, 0.17, 0.1] },
        { name: "versicolor", mean: [5.9, 2.8, 4.3, 1.3], sd: [0.5, 0.31, 0.47, 0.2] },
        { name: "virginica", mean: [6.6, 3.0, 5.5, 2.0], sd: [0.63, 0.32, 0.55, 0.27] },
      ];
      const rows: string[][] = [];
      for (const s of species) for (let i = 0; i < 60; i++) rows.push([...s.mean.map((m, j) => (m + rng.normal() * s.sd[j]!).toFixed(1)), s.name]);
      return { columns: ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"], rows: rng.shuffle(rows) };
    },
  },
  {
    id: "houses",
    name: "House prices",
    description: "Size, rooms, age, distance to the centre and a neighbourhood label predict a price. A regression problem with one categorical feature.",
    task: "regression",
    rows: 240,
    synthetic: true,
    suggestedTarget: "price",
    note: "Synthetic: prices follow a known formula plus noise, so you can check what the model recovers. 4% of ages are missing on purpose.",
    build: () => {
      const rng = new Rng(11);
      const hoods = [
        { name: "riverside", bump: 60 },
        { name: "old town", bump: 35 },
        { name: "suburb", bump: 0 },
        { name: "industrial", bump: -25 },
      ];
      const rows: string[][] = [];
      for (let i = 0; i < 240; i++) {
        const size = Math.round(55 + rng.next() * 190);
        const rooms = Math.max(1, Math.round(size / 45 + rng.normal() * 0.6));
        const age = Math.round(Math.max(0, 40 + rng.normal() * 22));
        const distance = Math.round((0.5 + rng.next() * 18) * 10) / 10;
        const hood = rng.pick(hoods);
        const price = 40 + size * 1.9 + rooms * 8 - age * 0.55 - distance * 4.2 + hood.bump + rng.normal() * 18;
        rows.push([String(size), String(rooms), rng.next() < 0.04 ? "" : String(age), String(distance), hood.name, (Math.round(price * 10) / 10).toString()]);
      }
      return { columns: ["size_m2", "rooms", "age_years", "distance_km", "neighbourhood", "price"], rows };
    },
  },
  {
    id: "churn",
    name: "Customer churn",
    description: "Tenure, monthly charge, plan, support tickets and a payment method predict whether a customer left. Imbalanced, with missing values and categories to encode.",
    task: "classification",
    rows: 400,
    synthetic: true,
    suggestedTarget: "churned",
    note: "Synthetic: churn probability follows a logistic rule over the features, with noise. About 30% churn; 5% of charges are missing on purpose.",
    build: () => {
      const rng = new Rng(23);
      const plans = ["basic", "standard", "premium"];
      const payments = ["card", "bank transfer", "wallet"];
      const rows: string[][] = [];
      for (let i = 0; i < 400; i++) {
        const tenure = Math.round(rng.next() * 60);
        const plan = rng.pick(plans);
        const charge = Math.round((plan === "basic" ? 15 : plan === "standard" ? 35 : 70) * (0.8 + rng.next() * 0.5) * 100) / 100;
        const tickets = Math.max(0, Math.round(rng.normal() * 1.4 + 1.2));
        const payment = rng.pick(payments);
        const autopay = rng.next() < 0.55;
        const z = -1.1 - tenure * 0.05 + charge * 0.018 + tickets * 0.55 - (autopay ? 0.8 : 0) + (payment === "wallet" ? 0.4 : 0) + rng.normal() * 0.6;
        const churned = 1 / (1 + Math.exp(-z)) > 0.5;
        rows.push([`C${1000 + i}`, String(tenure), rng.next() < 0.05 ? "" : String(charge), plan, String(tickets), payment, autopay ? "yes" : "no", churned ? "yes" : "no"]);
      }
      return { columns: ["customer_id", "tenure_months", "monthly_charge", "plan", "support_tickets", "payment_method", "autopay", "churned"], rows };
    },
  },
];

export function sampleInfo(): SampleDatasetInfo[] {
  return SAMPLES.map(({ id, name, description, task, rows, synthetic, suggestedTarget }) => ({ id, name, description, task, rows, synthetic, suggestedTarget }));
}
